1. ADD: introduce user interface in server system 2. POTENTIAL BUG: replace std::shared_future with std::future , std::async with std::thread::swap due to fatal  error C1001